# https://carlosbecker.com/posts/golang-completions-cobra/
---
before:
  hooks:
    - ./build/completions.sh
builds:
  - id: gotest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: gotest
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "gotest_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
dockers:
  - image_templates:
      - "ghcr.io/andriykalashnykov/gotest:latest"
      - "ghcr.io/andriykalashnykov/gotest:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
    skip_push: false

aurs:
  - package: |-
      # bin
      install -Dm755 "./gotest" "${pkgdir}/usr/bin/gotest"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gotest/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/gotest.bash" "${pkgdir}/usr/share/bash-completion/completions/gotest"
      install -Dm644 "./completions/gotest.zsh" "${pkgdir}/usr/share/zsh/site-functions/_gotest"
      install -Dm644 "./completionsgotest.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/gotest.fish"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/AndriyKalashnykov/gotest
    description: "GoTest app"
    maintainer: Andriy Kalashnykov <AndriyKalashnykov@gmail.com>
    license: MIT
    vendor: AndriyKalashnykov
    contents:
      - src: ./completions/gotest.bash
        dst: /etc/bash_completion.d/gotest
      - src: ./completions/gotest.fish
        dst: /usr/share/fish/completions/gotest.fish
      - src: ./completions/gotest.zsh
        dst: /usr/local/share/zsh/site-functions/_gotest
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl
      - golang
      - make
      - kind
